name: Hotfix Process

on:
  push:
    branches:
      - 'hotfix-*'  # Matches any branch that starts with 'hotfix-'

jobs:
  trigger-ci:
    name: Running CI pipeline
    uses: ./.github/workflows/CI.yml  # Calls the reusable workflow


#next steps would be to add the release pipelines here